import { Property } from './types';

export const MOCK_PROPERTIES: Property[] = [
  {
    id: '1',
    code: 'APC001',
    title: 'Apartamento de Luxo com Vista para o Mar',
    description: 'Espaçoso apartamento com acabamento em mármore, automação residencial completa e varanda gourmet. Localizado no coração da cidade com vista panorâmica.',
    purpose: 'SALE',
    propertyType: 'APARTMENT',
    price: 2500000,
    condominiumFee: 1800,
    iptu: 450,
    city: 'Rio de Janeiro',
    state: 'RJ',
    neighborhood: 'Barra da Tijuca',
    address: 'Av. Lúcio Costa, 3000',
    zipCode: '22630-010',
    bedrooms: 4,
    suites: 4,
    bathrooms: 6,
    parkingSpaces: 3,
    builtArea: 220,
    totalArea: 220,
    features: ['Ar condicionado', 'Varanda gourmet', 'Piscina', 'Academia', 'Portaria 24h'],
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1600607687940-4e7a6b85e4c7?auto=format&fit=crop&q=80&w=1200',
    ],
    latitude: -23.000,
    longitude: -43.350,
    status: 'AVAILABLE',
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    publishedAt: new Date().toISOString(),
  },
  {
    id: '2',
    code: 'CSA002',
    title: 'Casa Contemporânea em Condomínio Fechado',
    description: 'Projeto assinado por arquiteto renomado, integrando natureza e modernidade. Amplo jardim com paisagismo e iluminação LED.',
    purpose: 'SALE',
    propertyType: 'HOUSE',
    price: 4800000,
    condominiumFee: 2500,
    iptu: 1200,
    city: 'São Paulo',
    state: 'SP',
    neighborhood: 'Jardim Europa',
    address: 'Rua Groenlândia, 500',
    zipCode: '01434-000',
    bedrooms: 5,
    suites: 5,
    bathrooms: 7,
    parkingSpaces: 4,
    builtArea: 450,
    totalArea: 800,
    features: ['Sauna', 'Churrasqueira', 'Quintal', 'Depósito', 'Segurança privada'],
    images: [
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&q=80&w=1200',
    ],
    latitude: -23.580,
    longitude: -46.680,
    status: 'AVAILABLE',
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    publishedAt: new Date().toISOString(),
  },
  {
    id: '3',
    code: 'ALU003',
    title: 'Loft Industrial para Aluguel',
    description: 'Conceito aberto com pé direito duplo, tijolos aparentes e design moderno. Ideal para quem busca um estilo de vida urbano e sofisticado.',
    purpose: 'RENT',
    propertyType: 'APARTMENT',
    price: 8500,
    condominiumFee: 1200,
    iptu: 250,
    city: 'Curitiba',
    state: 'PR',
    neighborhood: 'Batel',
    address: 'Av. Sete de Setembro, 1200',
    zipCode: '80230-010',
    bedrooms: 1,
    suites: 1,
    bathrooms: 2,
    parkingSpaces: 1,
    builtArea: 95,
    totalArea: 95,
    features: ['Mobiliado', 'Lavanderia', 'Pet friendly', 'Coworking no prédio'],
    images: [
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&q=80&w=1200',
    ],
    latitude: -25.440,
    longitude: -49.280,
    status: 'AVAILABLE',
    featured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    publishedAt: new Date().toISOString(),
  },
  {
    id: '4',
    code: 'COM004',
    title: 'Sala Comercial Triple A',
    description: 'Conjunto comercial pronto para uso em edifício de alto padrão corporativo. Piso elevado, forro acústico e ar central.',
    purpose: 'SALE',
    propertyType: 'COMMERCIAL',
    price: 1200000,
    condominiumFee: 1500,
    iptu: 300,
    city: 'Porto Alegre',
    state: 'RS',
    neighborhood: 'Moinhos de Vento',
    address: 'Rua Padre Chagas, 100',
    zipCode: '90570-080',
    bedrooms: 0,
    suites: 0,
    bathrooms: 2,
    parkingSpaces: 2,
    builtArea: 80,
    totalArea: 80,
    features: ['Auditório', 'Estacionamento rotativo', 'Gerador', 'Fibra óptica'],
    images: [
      'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=1200',
    ],
    latitude: -30.020,
    longitude: -51.200,
    status: 'AVAILABLE',
    featured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    publishedAt: new Date().toISOString(),
  },
  {
    id: '5',
    code: 'COB005',
    title: 'Cobertura Duplex com Piscina Privativa',
    description: 'O ápice da exclusividade. Cobertura com área externa privativa, piscina aquecida e churrasqueira.',
    purpose: 'SALE',
    propertyType: 'APARTMENT',
    price: 3900000,
    condominiumFee: 3200,
    iptu: 800,
    city: 'Belo Horizonte',
    state: 'MG',
    neighborhood: 'Lourdes',
    address: 'Rua São Paulo, 2000',
    zipCode: '30170-132',
    bedrooms: 3,
    suites: 3,
    bathrooms: 5,
    parkingSpaces: 4,
    builtArea: 320,
    totalArea: 320,
    features: ['Piscina privativa', 'Espaço gourmet', 'Home office', 'SPA'],
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&q=80&w=1200',
    ],
    latitude: -19.930,
    longitude: -43.940,
    status: 'AVAILABLE',
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    publishedAt: new Date().toISOString(),
  },
  {
    id: '6',
    code: 'CSA006',
    title: 'Casa de Praia Design Minimalista',
    description: 'Localizada em condomínio de luxo à beira-mar. Ambientes integrados e muita luz natural.',
    purpose: 'SALE',
    propertyType: 'HOUSE',
    price: 2100000,
    condominiumFee: 900,
    iptu: 300,
    city: 'Florianópolis',
    state: 'SC',
    neighborhood: 'Jurerê Internacional',
    address: 'Alameda César Nascimento, 10',
    zipCode: '88053-500',
    bedrooms: 4,
    suites: 2,
    bathrooms: 4,
    parkingSpaces: 3,
    builtArea: 280,
    totalArea: 450,
    features: ['Beira-mar', 'Deck de madeira', 'Jardim vertical', 'Energia solar'],
    images: [
      'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?auto=format&fit=crop&q=80&w=1200',
    ],
    latitude: -27.440,
    longitude: -48.490,
    status: 'AVAILABLE',
    featured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    publishedAt: new Date().toISOString(),
  },
  {
    id: '7',
    code: 'APC007',
    title: 'Apartamento Studio Moderno',
    description: 'Compacto de luxo com marcenaria planejada de alto padrão. Perfeito para investidores ou jovens profissionais.',
    purpose: 'SALE',
    propertyType: 'APARTMENT',
    price: 650000,
    condominiumFee: 500,
    iptu: 120,
    city: 'Brasília',
    state: 'DF',
    neighborhood: 'Asa Sul',
    address: 'CLS 210, Bloco A',
    zipCode: '70273-510',
    bedrooms: 1,
    suites: 1,
    bathrooms: 1,
    parkingSpaces: 1,
    builtArea: 45,
    totalArea: 45,
    features: ['Portaria virtual', 'Lavanderia coletiva', 'Roof top', 'Academia'],
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=1200',
    ],
    latitude: -15.820,
    longitude: -47.900,
    status: 'AVAILABLE',
    featured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    publishedAt: new Date().toISOString(),
  },
  {
    id: '8',
    code: 'TER008',
    title: 'Terreno em Condomínio de Golf',
    description: 'Terreno plano com localização privilegiada frente ao campo de golf. Segurança e lazer incomparáveis.',
    purpose: 'SALE',
    propertyType: 'LAND',
    price: 850000,
    condominiumFee: 1100,
    iptu: 200,
    city: 'Campinas',
    state: 'SP',
    neighborhood: 'Gramado',
    address: 'Rodovia Heitor Penteado, km 6',
    zipCode: '13092-460',
    bedrooms: 0,
    suites: 0,
    bathrooms: 0,
    parkingSpaces: 0,
    builtArea: 0,
    totalArea: 1000,
    features: ['Campo de golf', 'Hípica', 'Lago', 'Trilha ecológica'],
    images: [
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&q=80&w=1200',
    ],
    latitude: -22.900,
    longitude: -47.000,
    status: 'AVAILABLE',
    featured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    publishedAt: new Date().toISOString(),
  }
];
